---
- name: Configure Server
  hosts: all
  become: yes

  tasks:
  - name: Install Nginx and PHP
    yum:
      name:
        - nginx
        - php-fpm
        - php-mysqlnd
      state: present

  - name: Create a dedicated user
    user:
      name: appuser
      state: present

  - name: Deploy a basic PHP application
    copy:
      content: |
        <?php
        echo "Hello, World!";
        ?>
      dest: /var/www/html/index.php
      mode: '0644'
    notify: restart nginx

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

  - name: Start and enbale Nginx service
    ansible.builtin.systemd:
      namle: nginx
      state: started
      enabled: yes
    become: yes
